import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import branchesRouter from "./branches";
import usersRouter from "./users";
import clientsRouter from "./clients";
import productsRouter from "./products";
import articlesRouter from "./articles";
import dashboardRouter from "./dashboard";
import creditProductsRouter from "./credit-products";
import sapCodesRouter from "./sap-codes";
import creditLinesRouter from "./credit-lines";
import miniAppRouter from "./mini-app";
import storageRouter from "./storage";
import aiRouter from "./ai";
import telegramRouter from "./telegram";
import collateralRouter from "./collateral";
import recommendationDocumentsRouter from "./recommendation-documents";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(telegramRouter);
router.use(aiRouter);
router.use(storageRouter);
router.use(branchesRouter);
router.use(usersRouter);
router.use(clientsRouter);
router.use(productsRouter);
router.use(articlesRouter);
router.use(dashboardRouter);
router.use(creditProductsRouter);
router.use(sapCodesRouter);
router.use(creditLinesRouter);
router.use(miniAppRouter);
router.use(collateralRouter);
router.use(recommendationDocumentsRouter);

export default router;
