import { db } from "@workspace/db";
import { creditProductsTable, sapCodesTable, creditLinesTable, basketItemsTable } from "@workspace/db";
import { sql } from "drizzle-orm";

// VERIFIED 2026-04-02: 20 products × 3 segments = 60 rows
// Products #9 HAMROH, #12 VOYAH, #13 LIXIANG, #14 Trend Motor have
// intentionally different rateUZS/loanAmount for средний vs микро/малый segments
// (matches original Ipak Yuli Bank product passport data)

async function seed() {
  console.log("Seeding credit products...");
  await db.delete(basketItemsTable);
  await db.delete(creditProductsTable);

  const creditProducts = [
    { number: 1, name: "ISHONCH", sapCode: "MMF_100", segment: "средний", disbursementForm: "перечислением", loanAmount: "до 100,0 млн.сум (в экв. иностр. валюты USD)", termWorkingCapital: "12 мес", termFixedAssets: "12 мес", termUntargeted: "-", rateUZS: "28%", rateUSD: "14%", rateEUR: "-", gracePeriod: "-", purpose: "Доверительные кредиты под залог страхового полиса или товаров в обороте.", highlight: "" },
    { number: 1, name: "ISHONCH", sapCode: "MMF_100", segment: "малый", disbursementForm: "перечислением", loanAmount: "до 100,0 млн.сум (в экв. иностр. валюты USD)", termWorkingCapital: "12 мес", termFixedAssets: "12 мес", termUntargeted: "-", rateUZS: "28%", rateUSD: "14%", rateEUR: "-", gracePeriod: "-", purpose: "Доверительные кредиты под залог страхового полиса или товаров в обороте.", highlight: "" },
    { number: 1, name: "ISHONCH", sapCode: "MMF_100", segment: "микро", disbursementForm: "Наличными и перечислением", loanAmount: "до 100,0 млн.сум (в экв. иностр. валюты USD)", termWorkingCapital: "12 мес", termFixedAssets: "12 мес", termUntargeted: "-", rateUZS: "28%", rateUSD: "14%", rateEUR: "-", gracePeriod: "-", purpose: "Доверительные кредиты под залог страхового полиса или товаров в обороте.", highlight: "" },
    { number: 2, name: "BUSINESS EXPRESS", sapCode: "MMF_EXP / M_EXP_USD", segment: "средний", disbursementForm: "перечислением на расчетный счет", loanAmount: "до 500,0 тыс. доллар США (в экв. национ. валюты UZS)", termWorkingCapital: "-", termFixedAssets: "0", termUntargeted: "до 60 месяцев для кредитов на сумму до 500 000,0 долларов США; свыше 60 месяцев для кредитов до 200 000,0 долларов США", rateUZS: "до 3 мес – 18%; до 6 мес – 19%; до 9 мес – 20%; до 12 мес – 21%; свыше 12 мес – не ниже 25%", rateUSD: "не ниже 14%", rateEUR: "-", gracePeriod: "до 6 мес.", purpose: "Нецелевой кредит для развития бизнеса. Удовлетворение потребностей клиентов в денежных средствах, в том числе для покупки сырья, покупки готовой продукции, оплаты работ и/или услуг и арендной платы, выплаты заработной платы сотрудникам, оплаты налогов, а также снятие наличных денежных средств с основного депозитного счета на прочие цели бизнеса.", highlight: "Особые условия: При сроке Кредита свыше 36 месяцев в качестве обеспечения принимаются недвижимость, заклад денежных средств и/или ювелирные изделия, золотые мерные слитки и золотые монеты ЦБ РУз. Для Кредитов на пополнение основного депозитного счета до востребования и/или на пополнение корпоративной банковской карты Заемщика – обязательно наличие основного депозитного счета до востребования, а также корпоративного карточного счета Заёмщика в Филиале." },
    { number: 2, name: "BUSINESS EXPRESS", sapCode: "MMF_EXP / M_EXP_USD", segment: "малый", disbursementForm: "перечислением на расчетный счет", loanAmount: "до 500,0 тыс. доллар США (в экв. национ. валюты UZS)", termWorkingCapital: "-", termFixedAssets: "0", termUntargeted: "до 60 месяцев для кредитов на сумму до 500 000,0 долларов США; свыше 60 месяцев для кредитов до 200 000,0 долларов США", rateUZS: "до 3 мес – 18%; до 6 мес – 19%; до 9 мес – 20%; до 12 мес – 21%; свыше 12 мес – не ниже 25%", rateUSD: "не ниже 14%", rateEUR: "-", gracePeriod: "до 6 мес.", purpose: "Нецелевой кредит для развития бизнеса.", highlight: "" },
    { number: 2, name: "BUSINESS EXPRESS", sapCode: "MMF_EXP / M_EXP_USD", segment: "микро", disbursementForm: "Наличными и перечислением", loanAmount: "до 500,0 тыс. доллар США (в экв. национ. валюты UZS)", termWorkingCapital: "-", termFixedAssets: "0", termUntargeted: "до 60 месяцев для кредитов на сумму до 500 000,0 долларов США; свыше 60 месяцев для кредитов до 200 000,0 долларов США", rateUZS: "до 3 мес – 18%; до 6 мес – 19%; до 9 мес – 20%; до 12 мес – 21%; свыше 12 мес – не ниже 25%", rateUSD: "не ниже 14%", rateEUR: "-", gracePeriod: "до 6 мес.", purpose: "Нецелевой кредит для развития бизнеса.", highlight: "" },
    { number: 3, name: "КРЕДИТЫ НА ВЫПЛАТУ ЗАРПЛАТЫ", sapCode: "", segment: "средний", disbursementForm: "перечислением", loanAmount: "до 200,0 млн.сум", termWorkingCapital: "разовый кредит - не более 3 мес; револьверный кредит - не более 12 мес.", termFixedAssets: "-", termUntargeted: "-", rateUZS: "не ниже 22%", rateUSD: "-", rateEUR: "-", gracePeriod: "-", purpose: "На выдачу заработной платы сотрудникам Заемщика. В начисленную заработную плату включаются удержания по налогу на доходы физических лиц и обязательные взносы.", highlight: "Кредиты на заработную плату не предоставляются: бюджетным организациям, органам государственной власти." },
    { number: 3, name: "КРЕДИТЫ НА ВЫПЛАТУ ЗАРПЛАТЫ", sapCode: "", segment: "малый", disbursementForm: "перечислением", loanAmount: "до 200,0 млн.сум", termWorkingCapital: "разовый кредит - не более 3 мес; револьверный кредит - не более 12 мес.", termFixedAssets: "-", termUntargeted: "-", rateUZS: "не ниже 22%", rateUSD: "-", rateEUR: "-", gracePeriod: "-", purpose: "На выдачу заработной платы сотрудникам Заемщика.", highlight: "" },
    { number: 3, name: "КРЕДИТЫ НА ВЫПЛАТУ ЗАРПЛАТЫ", sapCode: "", segment: "микро", disbursementForm: "перечислением", loanAmount: "до 200,0 млн.сум", termWorkingCapital: "разовый кредит - не более 3 мес; револьверный кредит - не более 12 мес.", termFixedAssets: "-", termUntargeted: "-", rateUZS: "не ниже 22%", rateUSD: "-", rateEUR: "-", gracePeriod: "-", purpose: "На выдачу заработной платы сотрудникам Заемщика.", highlight: "" },
    { number: 4, name: "ILK QADAM", sapCode: "MMF_SLF / M_SLF_USD / M_SLF_EUR", segment: "средний", disbursementForm: "перечислением", loanAmount: "до 1 000 000 000 (один миллиард) сум", termWorkingCapital: "36 мес", termFixedAssets: "60 мес", termUntargeted: "-", rateUZS: "до 3 мес – не ниже 18%; до 6 мес – не ниже 19%; до 9 мес – не ниже 20%; до 12 мес – не ниже 21%; свыше 12 мес – не ниже 25%", rateUSD: "до 12 мес – не ниже 13%; свыше 12 мес – не ниже 14%", rateEUR: "для импорта товаров – не ниже 13%", gracePeriod: "до 6 мес.", purpose: "Приобретение основных средств (новое оборудование, транспортные средства, включая грузовой транспорт, недвижимость) и пополнение оборотных средств.", highlight: "" },
    { number: 4, name: "ILK QADAM", sapCode: "MMF_SLF / M_SLF_USD / M_SLF_EUR", segment: "малый", disbursementForm: "перечислением", loanAmount: "до 1 000 000 000 (один миллиард) сум", termWorkingCapital: "36 мес", termFixedAssets: "60 мес", termUntargeted: "-", rateUZS: "до 3 мес – не ниже 18%; до 6 мес – не ниже 19%; до 9 мес – не ниже 20%; до 12 мес – не ниже 21%; свыше 12 мес – не ниже 25%", rateUSD: "до 12 мес – не ниже 13%; свыше 12 мес – не ниже 14%", rateEUR: "для импорта товаров – не ниже 13%", gracePeriod: "до 6 мес.", purpose: "Кредиты для развития бизнеса начинающих предпринимателей", highlight: "" },
    { number: 4, name: "ILK QADAM", sapCode: "MMF_SLF / M_SLF_USD / M_SLF_EUR", segment: "микро", disbursementForm: "Наличными и перечислением", loanAmount: "до 1 000 000 000 (один миллиард) сум", termWorkingCapital: "36 мес", termFixedAssets: "60 мес", termUntargeted: "-", rateUZS: "до 3 мес – не ниже 18%; до 6 мес – не ниже 19%; до 9 мес – не ниже 20%; до 12 мес – не ниже 21%; свыше 12 мес – не ниже 25%", rateUSD: "до 12 мес – не ниже 13%; свыше 12 мес – не ниже 14%", rateEUR: "для импорта товаров – не ниже 13%", gracePeriod: "до 6 мес.", purpose: "Кредиты для развития бизнеса начинающих предпринимателей", highlight: "" },
    { number: 5, name: "КРЕДИТЫ ДЛЯ РАЗВИТИЯ МАЛОГО БИЗНЕСА", sapCode: "", segment: "средний", disbursementForm: "Перечислением", loanAmount: "до 1,0 млн. доллар США (в экв. национ. валюты UZS)", termWorkingCapital: "36 мес", termFixedAssets: "60 мес", termUntargeted: "-", rateUZS: "до 3 мес - 17%; до 6 мес - 18%; до 9 мес - 19%; до 12 мес - 21%; до 18 мес - 22%; до 24 мес - 23%; до 36 мес - 25%; свыше 36 мес - 27%", rateUSD: "до 12 мес - 12%; до 18 мес - 13%; свыше 18 мес - 14%", rateEUR: "", gracePeriod: "до 6 мес.", purpose: "Кредитные средства выдаются на пополнение оборотных средств и увеличение основных средств для развития бизнеса.", highlight: "" },
    { number: 5, name: "КРЕДИТЫ ДЛЯ РАЗВИТИЯ МАЛОГО БИЗНЕСА", sapCode: "", segment: "малый", disbursementForm: "", loanAmount: "до 1,0 млн. доллар США (в экв. национ. валюты UZS)", termWorkingCapital: "36 мес", termFixedAssets: "60 мес", termUntargeted: "-", rateUZS: "до 3 мес - 17%; до 6 мес - 18%; до 9 мес - 19%; до 12 мес - 21%; до 24 мес - 23%; до 36 мес - 25%; свыше 36 мес - 27%", rateUSD: "до 12 мес - 13%; до 36 мес - 14%; свыше 36 мес - 15%", rateEUR: "", gracePeriod: "до 6 мес.", purpose: "Кредитные средства выдаются на пополнение оборотных средств и увеличение основных средств для развития бизнеса.", highlight: "" },
    { number: 5, name: "КРЕДИТЫ ДЛЯ РАЗВИТИЯ МАЛОГО БИЗНЕСА", sapCode: "", segment: "микро", disbursementForm: "", loanAmount: "до 1,0 млн. доллар США (в экв. национ. валюты UZS)", termWorkingCapital: "36 мес", termFixedAssets: "60 мес", termUntargeted: "-", rateUZS: "до 3 мес - 17%; до 6 мес - 18%; до 9 мес - 19%; до 12 мес - 21%; до 36 мес - 25%; свыше 36 мес - 27%", rateUSD: "до 36 мес - 14%; свыше 36 мес - 15%", rateEUR: "", gracePeriod: "до 6 мес.", purpose: "Кредитные средства выдаются на пополнение оборотных средств и увеличение основных средств для развития бизнеса.", highlight: "" },
    { number: 6, name: "BUSINESS IPOTEKA", sapCode: "MMF_IK / M_IK_USD", segment: "средний", disbursementForm: "Перечислением", loanAmount: "до 1,0 млн. доллар США (в экв. национ. валюты UZS)", termWorkingCapital: "-", termFixedAssets: "120 мес", termUntargeted: "-", rateUZS: "не ниже 22%", rateUSD: "не ниже 14%", rateEUR: "", gracePeriod: "до 12 мес.", purpose: "Кредитные средства выдаются на приобретение коммерческой недвижимости (офисные помещения, складские помещения, торговые помещения, производственные помещения) для ведения бизнеса.", highlight: "" },
    { number: 6, name: "BUSINESS IPOTEKA", sapCode: "MMF_IK / M_IK_USD", segment: "малый", disbursementForm: "", loanAmount: "до 1,0 млн. доллар США (в экв. национ. валюты UZS)", termWorkingCapital: "-", termFixedAssets: "120 мес", termUntargeted: "-", rateUZS: "не ниже 22%", rateUSD: "не ниже 14%", rateEUR: "", gracePeriod: "до 12 мес.", purpose: "Кредитные средства выдаются на приобретение коммерческой недвижимости.", highlight: "" },
    { number: 6, name: "BUSINESS IPOTEKA", sapCode: "MMF_IK / M_IK_USD", segment: "микро", disbursementForm: "", loanAmount: "до 1,0 млн. доллар США (в экв. национ. валюты UZS)", termWorkingCapital: "-", termFixedAssets: "120 мес", termUntargeted: "-", rateUZS: "не ниже 22%", rateUSD: "не ниже 14%", rateEUR: "", gracePeriod: "до 12 мес.", purpose: "Кредитные средства выдаются на приобретение коммерческой недвижимости.", highlight: "" },
    { number: 7, name: "EXPRESS MIKRO", sapCode: "MMF_ANDR / MMF_50 / MMF_200", segment: "средний", disbursementForm: "Наличными и перечислением", loanAmount: "от 50 до 200 млн.сум", termWorkingCapital: "18 мес", termFixedAssets: "36 мес", termUntargeted: "-", rateUZS: "не ниже 25%", rateUSD: "-", rateEUR: "-", gracePeriod: "до 3 мес.", purpose: "Пополнение оборотных и основных средств для развития бизнеса", highlight: "" },
    { number: 7, name: "EXPRESS MIKRO", sapCode: "MMF_ANDR / MMF_50 / MMF_200", segment: "малый", disbursementForm: "Наличными и перечислением", loanAmount: "от 50 до 200 млн.сум", termWorkingCapital: "18 мес", termFixedAssets: "36 мес", termUntargeted: "-", rateUZS: "не ниже 25%", rateUSD: "-", rateEUR: "-", gracePeriod: "до 3 мес.", purpose: "Пополнение оборотных и основных средств для развития бизнеса", highlight: "" },
    { number: 7, name: "EXPRESS MIKRO", sapCode: "MMF_ANDR / MMF_50 / MMF_200", segment: "микро", disbursementForm: "Наличными и перечислением", loanAmount: "от 50 до 200 млн.сум", termWorkingCapital: "18 мес", termFixedAssets: "36 мес", termUntargeted: "-", rateUZS: "не ниже 25%", rateUSD: "-", rateEUR: "-", gracePeriod: "до 3 мес.", purpose: "Пополнение оборотных и основных средств для развития бизнеса", highlight: "" },
    { number: 8, name: "GREEN ENERGY", sapCode: "MMF_GREEN", segment: "средний", disbursementForm: "перечислением", loanAmount: "до 500,0 тыс. доллар США (в экв. национ. валюты UZS)", termWorkingCapital: "-", termFixedAssets: "60 мес", termUntargeted: "-", rateUZS: "до 18 мес - 18%; до 36 мес - 20%; до 60 мес - 23%", rateUSD: "до 12 мес - 12%; до 18 мес - 13%; свыше 18 мес - 14%", rateEUR: "", gracePeriod: "до 6 мес.", purpose: "Кредитные средства на проекты в области «зелёной экономики»: солнечные панели, энергосберегающее оборудование, электромобили и станции зарядки.", highlight: "" },
    { number: 8, name: "GREEN ENERGY", sapCode: "MMF_GREEN", segment: "малый", disbursementForm: "", loanAmount: "до 500,0 тыс. доллар США (в экв. национ. валюты UZS)", termWorkingCapital: "-", termFixedAssets: "60 мес", termUntargeted: "-", rateUZS: "до 18 мес - 18%; до 36 мес - 20%; до 60 мес - 23%", rateUSD: "до 12 мес - 12%; до 18 мес - 13%; свыше 18 мес - 14%", rateEUR: "", gracePeriod: "до 6 мес.", purpose: "Кредитные средства на проекты в области «зелёной экономики».", highlight: "" },
    { number: 8, name: "GREEN ENERGY", sapCode: "MMF_GREEN", segment: "микро", disbursementForm: "", loanAmount: "до 500,0 тыс. доллар США (в экв. национ. валюты UZS)", termWorkingCapital: "-", termFixedAssets: "60 мес", termUntargeted: "-", rateUZS: "до 18 мес - 18%; до 36 мес - 20%; до 60 мес - 23%", rateUSD: "до 12 мес - 12%; до 18 мес - 13%; свыше 18 мес - 14%", rateEUR: "", gracePeriod: "до 6 мес.", purpose: "Кредитные средства на проекты в области «зелёной экономики».", highlight: "" },
    { number: 9, name: "HAMROH (для женщин-предпринимателей)", sapCode: "MMF_HAM", segment: "средний", disbursementForm: "перечислением на расчетный счет", loanAmount: "Условия финансирования I: до 1000-кратного размера БРВ на один проект с условием", termWorkingCapital: "24 мес", termFixedAssets: "84 мес", termUntargeted: "-", rateUZS: "Срок до 18 месяцев: На приобр.основных средств: при первоначальном взносе 30%", rateUSD: "-", rateEUR: "-", gracePeriod: "для пополнения оборотных средств – до 6 месяцев; для приобретения основных средств – до 12 месяцев", purpose: "Кредитные средства выдаются на развитие деятельности субъектов малого и среднего бизнеса, где женщины являются собственниками или соучредителями.", highlight: "" },
    { number: 9, name: "HAMROH (для женщин-предпринимателей)", sapCode: "MMF_HAM", segment: "малый", disbursementForm: "перечислением на расчетный счет", loanAmount: "Условия финансирования I: до 1000-кратного размера БРВ", termWorkingCapital: "24 мес", termFixedAssets: "84 мес", termUntargeted: "-", rateUZS: "", rateUSD: "-", rateEUR: "-", gracePeriod: "для пополнения оборотных средств – до 6 месяцев; для приобретения основных средств – до 12 месяцев", purpose: "Кредитные средства выдаются на развитие деятельности субъектов малого и среднего бизнеса.", highlight: "" },
    { number: 9, name: "HAMROH (для женщин-предпринимателей)", sapCode: "MMF_HAM", segment: "микро", disbursementForm: "перечислением на расчетный счет", loanAmount: "Условия финансирования I: до 1000-кратного размера БРВ", termWorkingCapital: "24 мес", termFixedAssets: "84 мес", termUntargeted: "-", rateUZS: "", rateUSD: "-", rateEUR: "-", gracePeriod: "для пополнения оборотных средств – до 6 месяцев; для приобретения основных средств – до 12 месяцев", purpose: "Кредитные средства выдаются на развитие деятельности субъектов малого и среднего бизнеса.", highlight: "" },
    { number: 10, name: "ISUZU", sapCode: "MMF_AVK", segment: "средний", disbursementForm: "Перечислением на расчетный счет Продавца", loanAmount: "до 1,0 млн. доллар США (в экв. национ. валюты UZS)", termWorkingCapital: "-", termFixedAssets: "48 мес.", termUntargeted: "-", rateUZS: "Первоначальный взнос — не ниже 25%; до 24 месяцев — 18%; до 36 месяцев — 20%; до 48 месяцев — 22%", rateUSD: "-", rateEUR: "-", gracePeriod: "-", purpose: "Кредитные средства выдаются на приобретение автотранспортных средств марки ISUZU для субъектов предпринимательства.", highlight: "" },
    { number: 10, name: "ISUZU", sapCode: "MMF_AVK", segment: "малый", disbursementForm: "", loanAmount: "до 1,0 млн. доллар США (в экв. национ. валюты UZS)", termWorkingCapital: "-", termFixedAssets: "48 мес.", termUntargeted: "-", rateUZS: "Первоначальный взнос — не ниже 25%; до 24 месяцев — 18%; до 36 месяцев — 20%; до 48 месяцев — 22%", rateUSD: "-", rateEUR: "-", gracePeriod: "-", purpose: "Кредитные средства на приобретение автотранспортных средств марки ISUZU.", highlight: "" },
    { number: 10, name: "ISUZU", sapCode: "MMF_AVK", segment: "микро", disbursementForm: "", loanAmount: "до 1,0 млн. доллар США (в экв. национ. валюты UZS)", termWorkingCapital: "-", termFixedAssets: "48 мес.", termUntargeted: "-", rateUZS: "Первоначальный взнос — не ниже 25%; до 24 месяцев — 18%; до 36 месяцев — 20%; до 48 месяцев — 22%", rateUSD: "-", rateEUR: "-", gracePeriod: "-", purpose: "Кредитные средства на приобретение автотранспортных средств марки ISUZU.", highlight: "" },
    { number: 11, name: "FOTON", sapCode: "MMF_FOTON", segment: "средний", disbursementForm: "Перечислением на расчетный счет Продавца", loanAmount: "до 1,0 млн. доллар США (в экв. национ. валюты UZS)", termWorkingCapital: "-", termFixedAssets: "48 мес. (В зависимости от % перв.взноса)", termUntargeted: "-", rateUZS: "0%", rateUSD: "-", rateEUR: "-", gracePeriod: "до 6 мес.", purpose: "Выдача автокредитов для индивидуальных предпринимателей и юридическим лицам на приобретение автотранспорта марки FOTON.", highlight: "При первоначальном взносе 0% — до 12 месяцев; 30% — до 18 месяцев; 40% — до 22 месяцев" },
    { number: 11, name: "FOTON", sapCode: "MMF_FOTON", segment: "малый", disbursementForm: "", loanAmount: "до 1,0 млн. доллар США (в экв. национ. валюты UZS)", termWorkingCapital: "-", termFixedAssets: "48 мес.", termUntargeted: "-", rateUZS: "0%", rateUSD: "-", rateEUR: "-", gracePeriod: "до 6 мес.", purpose: "Автокредиты на приобретение автотранспорта марки FOTON.", highlight: "" },
    { number: 11, name: "FOTON", sapCode: "MMF_FOTON", segment: "микро", disbursementForm: "", loanAmount: "до 1,0 млн. доллар США (в экв. национ. валюты UZS)", termWorkingCapital: "-", termFixedAssets: "48 мес.", termUntargeted: "-", rateUZS: "0%", rateUSD: "-", rateEUR: "-", gracePeriod: "до 6 мес.", purpose: "Автокредиты на приобретение автотранспорта марки FOTON.", highlight: "" },
    { number: 12, name: "VOYAH", sapCode: "MMF_VYH", segment: "средний", disbursementForm: "Перечислением на расчетный счет Продавца", loanAmount: "до 1,0 млн. доллар США (в экв. национ. валюты UZS)", termWorkingCapital: "-", termFixedAssets: "48 мес.", termUntargeted: "-", rateUZS: "При первоначальном взносе от 30% — 25%; При первоначальном взносе от 40% — 24%", rateUSD: "-", rateEUR: "-", gracePeriod: "до 6 мес.", purpose: "Кредитные средства выдаются на приобретение автотранспортных средств марки VOYAH для субъектов предпринимательства.", highlight: "" },
    { number: 12, name: "VOYAH", sapCode: "MMF_VYH", segment: "малый", disbursementForm: "", loanAmount: "до 1,0 млн. доллар США (в экв. национ. валюты UZS)", termWorkingCapital: "-", termFixedAssets: "48 мес.", termUntargeted: "-", rateUZS: "", rateUSD: "-", rateEUR: "-", gracePeriod: "до 6 мес.", purpose: "Кредитные средства на приобретение автотранспортных средств марки VOYAH.", highlight: "" },
    { number: 12, name: "VOYAH", sapCode: "MMF_VYH", segment: "микро", disbursementForm: "", loanAmount: "до 1,0 млн. доллар США (в экв. национ. валюты UZS)", termWorkingCapital: "-", termFixedAssets: "48 мес.", termUntargeted: "-", rateUZS: "", rateUSD: "-", rateEUR: "-", gracePeriod: "до 6 мес.", purpose: "Кредитные средства на приобретение автотранспортных средств марки VOYAH.", highlight: "" },
    { number: 13, name: "LIXIANG", sapCode: "M_AVK_LI", segment: "средний", disbursementForm: "Перечислением на расчетный счет Продавца", loanAmount: "до 1,0 млн. доллар США (в экв. национ. валюты UZS)", termWorkingCapital: "-", termFixedAssets: "60 мес.", termUntargeted: "-", rateUZS: "При первоначальном взносе 30%: до 12 месяцев — 12%; до 18 месяцев — 17%; до 24 месяцев — 20%", rateUSD: "-", rateEUR: "-", gracePeriod: "до 6 мес.", purpose: "Кредитные средства выдаются на приобретение автотранспортных средств для субъектов предпринимательства.", highlight: "" },
    { number: 13, name: "LIXIANG", sapCode: "M_AVK_LI", segment: "малый", disbursementForm: "", loanAmount: "до 1,0 млн. доллар США (в экв. национ. валюты UZS)", termWorkingCapital: "-", termFixedAssets: "60 мес.", termUntargeted: "-", rateUZS: "", rateUSD: "-", rateEUR: "-", gracePeriod: "до 6 мес.", purpose: "Кредитные средства на приобретение автотранспортных средств.", highlight: "" },
    { number: 13, name: "LIXIANG", sapCode: "M_AVK_LI", segment: "микро", disbursementForm: "", loanAmount: "до 1,0 млн. доллар США (в экв. национ. валюты UZS)", termWorkingCapital: "-", termFixedAssets: "60 мес.", termUntargeted: "-", rateUZS: "", rateUSD: "-", rateEUR: "-", gracePeriod: "до 6 мес.", purpose: "Кредитные средства на приобретение автотранспортных средств.", highlight: "" },
    { number: 14, name: "Trend Motor", sapCode: "MMF_TRM", segment: "средний", disbursementForm: "Перечислением на расчетный счет Продавца", loanAmount: "до 100 000,0 (сто тысяч) долларов США (в экв. национ. валюты UZS)", termWorkingCapital: "-", termFixedAssets: "60 мес.", termUntargeted: "-", rateUZS: "Первоначальный взнос — от 30%; до 12 месяцев — 20%; свыше 12 до 36 месяцев — 22%", rateUSD: "-", rateEUR: "-", gracePeriod: "до 6 мес.", purpose: "Кредитные средства на приобретение автотранспортных средств для субъектов предпринимательства.", highlight: "" },
    { number: 14, name: "Trend Motor", sapCode: "MMF_TRM", segment: "малый", disbursementForm: "", loanAmount: "до 100 000,0 долларов США (в экв. национ. валюты UZS)", termWorkingCapital: "-", termFixedAssets: "60 мес.", termUntargeted: "-", rateUZS: "", rateUSD: "-", rateEUR: "-", gracePeriod: "до 6 мес.", purpose: "Кредитные средства на приобретение автотранспортных средств.", highlight: "" },
    { number: 14, name: "Trend Motor", sapCode: "MMF_TRM", segment: "микро", disbursementForm: "", loanAmount: "до 100 000,0 долларов США (в экв. национ. валюты UZS)", termWorkingCapital: "-", termFixedAssets: "60 мес.", termUntargeted: "-", rateUZS: "", rateUSD: "-", rateEUR: "-", gracePeriod: "до 6 мес.", purpose: "Кредитные средства на приобретение автотранспортных средств.", highlight: "" },
    { number: 15, name: "Онлайн кредит", sapCode: "", segment: "средний", disbursementForm: "путем зачисления денежных средств со ссудного счета на основной депозитный счет до востребования Заемщика", loanAmount: "до 200,0 млн.сум", termWorkingCapital: "12 мес.", termFixedAssets: "-", termUntargeted: "-", rateUZS: "30%", rateUSD: "-", rateEUR: "-", gracePeriod: "-", purpose: "Поддержка и развитие предпринимательской деятельности, а также удовлетворение потребностей клиентов в денежных средствах.", highlight: "Особое условие – наличие основного депозитного счета до востребования Заемщика в Филиале." },
    { number: 15, name: "Онлайн кредит", sapCode: "", segment: "малый", disbursementForm: "", loanAmount: "до 200,0 млн.сум", termWorkingCapital: "12 мес.", termFixedAssets: "-", termUntargeted: "-", rateUZS: "30%", rateUSD: "-", rateEUR: "-", gracePeriod: "-", purpose: "Поддержка и развитие предпринимательской деятельности.", highlight: "" },
    { number: 15, name: "Онлайн кредит", sapCode: "", segment: "микро", disbursementForm: "", loanAmount: "до 200,0 млн.сум", termWorkingCapital: "12 мес.", termFixedAssets: "-", termUntargeted: "-", rateUZS: "30%", rateUSD: "-", rateEUR: "-", gracePeriod: "-", purpose: "Поддержка и развитие предпринимательской деятельности.", highlight: "" },
    { number: 16, name: "ПЛАНШЕТНОЕ КРЕДИТОВАНИЕ", sapCode: "", segment: "средний", disbursementForm: "путем зачисления на расчётный счёт Заемщика", loanAmount: "до 500,0 млн.сум", termWorkingCapital: "12 мес.", termFixedAssets: "36 мес.", termUntargeted: "-", rateUZS: "не ниже 25%", rateUSD: "-", rateEUR: "-", gracePeriod: "до 3 мес.", purpose: "Планшетное кредитование — оперативная выдача кредитов с использованием мобильного устройства кредитного эксперта в полевых условиях.", highlight: "Решение принимается на месте через планшет/мобильное устройство эксперта. Упрощённый пакет документов." },
    { number: 16, name: "ПЛАНШЕТНОЕ КРЕДИТОВАНИЕ", sapCode: "", segment: "малый", disbursementForm: "", loanAmount: "до 500,0 млн.сум", termWorkingCapital: "12 мес.", termFixedAssets: "36 мес.", termUntargeted: "-", rateUZS: "не ниже 25%", rateUSD: "-", rateEUR: "-", gracePeriod: "до 3 мес.", purpose: "Планшетное кредитование — оперативная выдача кредитов через мобильное устройство.", highlight: "" },
    { number: 16, name: "ПЛАНШЕТНОЕ КРЕДИТОВАНИЕ", sapCode: "", segment: "микро", disbursementForm: "", loanAmount: "до 500,0 млн.сум", termWorkingCapital: "12 мес.", termFixedAssets: "36 мес.", termUntargeted: "-", rateUZS: "не ниже 25%", rateUSD: "-", rateEUR: "-", gracePeriod: "до 3 мес.", purpose: "Планшетное кредитование — оперативная выдача кредитов через мобильное устройство.", highlight: "" },
    { number: 17, name: "BIZNESNI RIVOJLANTIRISH", sapCode: "", segment: "средний", disbursementForm: "Перечислением", loanAmount: "до 5,0 млрд.сум", termWorkingCapital: "36 мес.", termFixedAssets: "60 мес.", termUntargeted: "-", rateUZS: "до 3 мес - 17%; до 6 мес - 18%; до 12 мес - 21%; до 36 мес - 25%; свыше 36 мес - 27%", rateUSD: "не ниже 14%", rateEUR: "-", gracePeriod: "до 6 мес.", purpose: "Кредитные средства на развитие предпринимательской деятельности, пополнение оборотных и основных средств.", highlight: "" },
    { number: 17, name: "BIZNESNI RIVOJLANTIRISH", sapCode: "", segment: "малый", disbursementForm: "", loanAmount: "до 5,0 млрд.сум", termWorkingCapital: "36 мес.", termFixedAssets: "60 мес.", termUntargeted: "-", rateUZS: "до 3 мес - 17%; до 6 мес - 18%; до 12 мес - 21%; до 36 мес - 25%; свыше 36 мес - 27%", rateUSD: "не ниже 14%", rateEUR: "-", gracePeriod: "до 6 мес.", purpose: "Кредитные средства на развитие предпринимательской деятельности.", highlight: "" },
    { number: 17, name: "BIZNESNI RIVOJLANTIRISH", sapCode: "", segment: "микро", disbursementForm: "", loanAmount: "до 5,0 млрд.сум", termWorkingCapital: "36 мес.", termFixedAssets: "60 мес.", termUntargeted: "-", rateUZS: "до 3 мес - 17%; до 6 мес - 18%; до 12 мес - 21%; до 36 мес - 25%; свыше 36 мес - 27%", rateUSD: "не ниже 14%", rateEUR: "-", gracePeriod: "до 6 мес.", purpose: "Кредитные средства на развитие предпринимательской деятельности.", highlight: "" },
    { number: 18, name: "MAHALLA LOYIHASI", sapCode: "MMF_MAH", segment: "средний", disbursementForm: "Перечислением на расчётный счёт", loanAmount: "до 1 000,0 млн.сум", termWorkingCapital: "24 мес.", termFixedAssets: "60 мес.", termUntargeted: "-", rateUZS: "до 18 мес - 18%; до 36 мес - 20%; свыше 36 мес - 22%", rateUSD: "-", rateEUR: "-", gracePeriod: "до 6 мес.", purpose: "Кредитные средства для предпринимателей на территории махаллей для развития малого бизнеса, ремесленничества и надомного труда.", highlight: "Целевая программа для развития предпринимательства в махаллях. Льготные условия." },
    { number: 18, name: "MAHALLA LOYIHASI", sapCode: "MMF_MAH", segment: "малый", disbursementForm: "", loanAmount: "до 1 000,0 млн.сум", termWorkingCapital: "24 мес.", termFixedAssets: "60 мес.", termUntargeted: "-", rateUZS: "до 18 мес - 18%; до 36 мес - 20%; свыше 36 мес - 22%", rateUSD: "-", rateEUR: "-", gracePeriod: "до 6 мес.", purpose: "Кредитные средства для развития малого бизнеса в махаллях.", highlight: "" },
    { number: 18, name: "MAHALLA LOYIHASI", sapCode: "MMF_MAH", segment: "микро", disbursementForm: "", loanAmount: "до 1 000,0 млн.сум", termWorkingCapital: "24 мес.", termFixedAssets: "60 мес.", termUntargeted: "-", rateUZS: "до 18 мес - 18%; до 36 мес - 20%; свыше 36 мес - 22%", rateUSD: "-", rateEUR: "-", gracePeriod: "до 6 мес.", purpose: "Кредитные средства для развития малого бизнеса в махаллях.", highlight: "" },
    { number: 19, name: "KICHIK VA O'RTA BIZNESNI MOLIYAVIY QO'LLAB-QUVVATLASH", sapCode: "", segment: "средний", disbursementForm: "Перечислением", loanAmount: "до 2,0 млн. доллар США (в экв. национ. валюты UZS)", termWorkingCapital: "36 мес.", termFixedAssets: "84 мес.", termUntargeted: "-", rateUZS: "до 12 мес - 18%; до 24 мес - 20%; до 36 мес - 22%; свыше 36 мес - 24%", rateUSD: "не ниже 13%", rateEUR: "-", gracePeriod: "до 12 мес.", purpose: "Финансовая поддержка субъектов малого и среднего бизнеса для развития предпринимательской деятельности.", highlight: "" },
    { number: 19, name: "KICHIK VA O'RTA BIZNESNI MOLIYAVIY QO'LLAB-QUVVATLASH", sapCode: "", segment: "малый", disbursementForm: "", loanAmount: "до 2,0 млн. доллар США (в экв. национ. валюты UZS)", termWorkingCapital: "36 мес.", termFixedAssets: "84 мес.", termUntargeted: "-", rateUZS: "до 12 мес - 18%; до 24 мес - 20%; до 36 мес - 22%; свыше 36 мес - 24%", rateUSD: "не ниже 13%", rateEUR: "-", gracePeriod: "до 12 мес.", purpose: "Финансовая поддержка субъектов малого и среднего бизнеса.", highlight: "" },
    { number: 19, name: "KICHIK VA O'RTA BIZNESNI MOLIYAVIY QO'LLAB-QUVVATLASH", sapCode: "", segment: "микро", disbursementForm: "", loanAmount: "до 2,0 млн. доллар США (в экв. национ. валюты UZS)", termWorkingCapital: "36 мес.", termFixedAssets: "84 мес.", termUntargeted: "-", rateUZS: "до 12 мес - 18%; до 24 мес - 20%; до 36 мес - 22%; свыше 36 мес - 24%", rateUSD: "не ниже 13%", rateEUR: "-", gracePeriod: "до 12 мес.", purpose: "Финансовая поддержка субъектов малого и среднего бизнеса.", highlight: "" },
    { number: 20, name: "BIZNESGA KO'MAK", sapCode: "", segment: "средний", disbursementForm: "Перечислением на расчётный счёт", loanAmount: "до 500,0 млн.сум", termWorkingCapital: "24 мес.", termFixedAssets: "48 мес.", termUntargeted: "-", rateUZS: "до 12 мес - 20%; до 24 мес - 22%; свыше 24 мес - 24%", rateUSD: "-", rateEUR: "-", gracePeriod: "до 3 мес.", purpose: "Кредитные средства на поддержку и развитие малого бизнеса, в том числе для начинающих предпринимателей.", highlight: "" },
    { number: 20, name: "BIZNESGA KO'MAK", sapCode: "", segment: "малый", disbursementForm: "", loanAmount: "до 500,0 млн.сум", termWorkingCapital: "24 мес.", termFixedAssets: "48 мес.", termUntargeted: "-", rateUZS: "до 12 мес - 20%; до 24 мес - 22%; свыше 24 мес - 24%", rateUSD: "-", rateEUR: "-", gracePeriod: "до 3 мес.", purpose: "Кредитные средства на поддержку и развитие малого бизнеса.", highlight: "" },
    { number: 20, name: "BIZNESGA KO'MAK", sapCode: "", segment: "микро", disbursementForm: "", loanAmount: "до 500,0 млн.сум", termWorkingCapital: "24 мес.", termFixedAssets: "48 мес.", termUntargeted: "-", rateUZS: "до 12 мес - 20%; до 24 мес - 22%; свыше 24 мес - 24%", rateUSD: "-", rateEUR: "-", gracePeriod: "до 3 мес.", purpose: "Кредитные средства на поддержку и развитие малого бизнеса.", highlight: "" },
  ];

  for (const cp of creditProducts) {
    await db.insert(creditProductsTable).values(cp);
  }
  console.log(`Inserted ${creditProducts.length} credit products`);

  console.log("Seeding SAP codes...");
  await db.delete(sapCodesTable);

  const sapCodes = [
    { status: "действующий", productId: "ANDR_USD", name: "EXPRESS MIKRO ВАЛЮТНЫЙ", productType: "Финансовые услуги", categoryId: "BFS_ORG_LOANI", categoryName: "Кредиты за счет ин. капитала" },
    { status: "действующий", productId: "BXM", name: "Кредит ММФ за счет собственных средств", productType: "Финансовые услуги", categoryId: "BFS_ORG_LOANO", categoryName: "Кредиты за счет собств. средств" },
    { status: "действующий", productId: "BXM_ADB'", name: "Кредит ММФ за счет линии АБР наличный", productType: "Финансовые услуги", categoryId: "BFS_ORG_LOANI", categoryName: "Кредиты за счет ин. капитала" },
    { status: "действующий", productId: "BXM_BMF", name: "Кредит ММФ за счет линии BlueOrchard", productType: "Финансовые услуги", categoryId: "BFS_ORG_LOANI", categoryName: "Кредиты за счет ин. капитала" },
    { status: "действующий", productId: "BXM_DKM", name: "Кредит ММФ за счет линии MIKROFINANZFOND", productType: "Финансовые услуги", categoryId: "BFS_ORG_LOANI", categoryName: "Кредиты за счет ин. капитала" },
    { status: "действующий", productId: "BXM_EUR", name: "Кредит ММФ за счет собств.средств ЕВРО", productType: "Финансовые услуги", categoryId: "BFS_ORG_LOANO", categoryName: "Кредиты за счет собств. средств" },
    { status: "действующий", productId: "BXM_EXP", name: "BUSINESS EXPRESS", productType: "Финансовые услуги", categoryId: "BFS_ORG_LOANO", categoryName: "Кредиты за счет собств. средств" },
    { status: "действующий", productId: "BXM_SLF", name: "Кредит ММФ \"Первый шаг\" нац валюта", productType: "Финансовые услуги", categoryId: "BFS_ORG_LOANI", categoryName: "Кредиты за счет ин. капитала" },
    { status: "действующий", productId: "BXM_SYMB", name: "Кредит ММФ за счет линии Symbiotics S.A", productType: "Финансовые услуги", categoryId: "BFS_ORG_LOANI", categoryName: "Кредиты за счет ин. капитала" },
    { status: "действующий", productId: "BXM_USD", name: "Кредит ММФ за счет собств.средств ДОЛ", productType: "Финансовые услуги", categoryId: "BFS_ORG_LOANO", categoryName: "Кредиты за счет собств. средств" },
    { status: "заблокировать", productId: "BXM_WEFI", name: "Кредит ММФ \"Женщина предприниматель\"", productType: "Финансовые услуги", categoryId: "BFS_ORG_LOANI", categoryName: "Кредиты за счет ин. капитала" },
    { status: "действующий", productId: "B_ADB2_US", name: "Кредит ММФ за счет линии АБР 2 фаза", productType: "Финансовые услуги", categoryId: "BFS_ORG_LOANI", categoryName: "Кредиты за счет ин. капитала" },
    { status: "действующий", productId: "B_SLF_AVK", name: "Кредит ММФ \"Первый шаг\" (авто кредит)", productType: "Финансовые услуги", categoryId: "BFS_ORG_LOANO", categoryName: "Кредиты за счет собств. средств" },
    { status: "действующий", productId: "B_SLF_EUR", name: "Кредит ММФ \"Первый шаг\" иност валют ЕВРО", productType: "Финансовые услуги", categoryId: "BFS_ORG_LOANO", categoryName: "Кредиты за счет собств. средств" },
    { status: "действующий", productId: "B_SLF_USD", name: "Кредит ММФ \"Первый шаг\" иност валюта", productType: "Финансовые услуги", categoryId: "BFS_ORG_LOANI", categoryName: "Кредиты за счет ин. капитала" },
    { status: "действующий", productId: "MGA_USD", name: "Валютный кредит ММФ в рамках ГС, АБР", productType: "Финансовые услуги", categoryId: "BFS_ORG_LOANI", categoryName: "Кредиты за счет ин. капитала" },
    { status: "действующий", productId: "MG_USD", name: "Валют кредит ММФ в рамках ГС,собств. ср.", productType: "Финансовые услуги", categoryId: "BFS_ORG_LOANO", categoryName: "Кредиты за счет собств. средств" },
    { status: "действующий", productId: "MMF", name: "Кредит ММФ за счет собственных средств", productType: "Финансовые услуги", categoryId: "BFS_ORG_LOANO", categoryName: "Кредиты за счет собств. средств" },
    { status: "действующий", productId: "MMF'", name: "Кредит ММФ за счет собственных средств", productType: "Финансовые услуги", categoryId: "BFS_ORG_LOANO", categoryName: "Кредиты за счет собств. средств" },
    { status: "действующий", productId: "MMF_100", name: "EXPRESS MIKRO 100", productType: "Финансовые услуги", categoryId: "BFS_ORG_LOANI", categoryName: "Кредиты за счет ин. капитала" },
    { status: "действующий", productId: "MMF_200", name: "EXPRESS MIKRO 200", productType: "Финансовые услуги", categoryId: "BFS_ORG_LOANI", categoryName: "Кредиты за счет ин. капитала" },
    { status: "заблокировать", productId: "MMF_200_USD", name: "EXPRESS MIKRO 200 Доллар", productType: "Финансовые услуги", categoryId: "BFS_ORG_LOANI", categoryName: "Кредиты за счет ин. капитала" },
    { status: "действующий", productId: "MMF_50", name: "EXPRESS MIKRO 50", productType: "Финансовые услуги", categoryId: "BFS_ORG_LOANI", categoryName: "Кредиты за счет ин. капитала" },
    { status: "действующий", productId: "MMF_ADB", name: "Кредит ММФ за счет линии АБР", productType: "Финансовые услуги", categoryId: "BFS_ORG_LOANI", categoryName: "Кредиты за счет ин. капитала" },
    { status: "действующий", productId: "MMF_ADB'", name: "Кредит ММФ за счет линии АБР наличный", productType: "Финансовые услуги", categoryId: "BFS_ORG_LOANI", categoryName: "Кредиты за счет ин. капитала" },
    { status: "действующий", productId: "MMF_ANDR", name: "EXPRESS MIKRO", productType: "Финансовые услуги", categoryId: "BFS_ORG_LOANO", categoryName: "Кредиты за счет собств. средств" },
    { status: "действующий", productId: "MMF_AVK", name: "Автокредит для спец ISUZU", productType: "Финансовые услуги", categoryId: "BFS_ORG_LOANO", categoryName: "Кредиты за счет собств. средств" },
    { status: "действующий", productId: "MMF_BIB", name: "Кредит ММФ за счет линии BIB", productType: "Финансовые услуги", categoryId: "BFS_ORG_LOANI", categoryName: "Кредиты за счет ин. капитала" },
    { status: "действующий", productId: "MMF_BMF", name: "Кредит ММФ за счет линии BlueOrchard", productType: "Финансовые услуги", categoryId: "BFS_ORG_LOANI", categoryName: "Кредиты за счет ин. капитала" },
    { status: "заблокировать", productId: "MMF_BOV", name: "Кредит ММФ Бизнес-овердрафт", productType: "Финансовые услуги", categoryId: "BFS_ORG_LOANO", categoryName: "Кредиты за счет собств. средств" },
    { status: "действующий", productId: "MMF_DEG", name: "Кредит ММФ за счет линии ДЕГ", productType: "Финансовые услуги", categoryId: "BFS_ORG_LOANI", categoryName: "Кредиты за счет ин. капитала" },
    { status: "действующий", productId: "MMF_DKM", name: "Кредит ММФ за счет линии MIKROFINANZFOND", productType: "Финансовые услуги", categoryId: "BFS_ORG_LOANI", categoryName: "Кредиты за счет ин. капитала" },
    { status: "заблокировать", productId: "MMF_EBRD", name: "Кредит ММФ за счет линии ЕБРР", productType: "Финансовые услуги", categoryId: "BFS_ORG_LOANI", categoryName: "Кредиты за счет ин. капитала" },
    { status: "действующий", productId: "MMF_ECAR", name: "Кредит ММФ по продукту \"Electro-Car\"", productType: "Финансовые услуги", categoryId: "BFS_ORG_LOANO", categoryName: "Кредиты за счет собств. средств" },
    { status: "действующий", productId: "MMF_EUR", name: "Кредит ММФ за счет собств.средств ЕВРО", productType: "Финансовые услуги", categoryId: "BFS_ORG_LOANO", categoryName: "Кредиты за счет собств. средств" },
    { status: "действующий", productId: "MMF_EXP", name: "BUSINESS EXPRESS", productType: "Финансовые услуги", categoryId: "BFS_ORG_LOANO", categoryName: "Кредиты за счет собств. средств" },
    { status: "действующий", productId: "MMF_FACT", name: "Факторинг - невозоб. ММСБ (нац. вал)", productType: "Финансовые услуги", categoryId: "BFS_ORG_LOANO", categoryName: "Кредиты за счет собств. средств" },
    { status: "действующий", productId: "MMF_FMO", name: "Кредит ММФ за счет линии ФМО", productType: "Финансовые услуги", categoryId: "BFS_ORG_LOANI", categoryName: "Кредиты за счет ин. капитала" },
    { status: "действующий", productId: "MMF_FOTON", name: "Автокредит для спец FOTON", productType: "Финансовые услуги", categoryId: "BFS_ORG_LOANO", categoryName: "Кредиты за счет собств. средств" },
    { status: "действующий", productId: "MMF_GH", name: "Для приобретения хлопкового волокна", productType: "Финансовые услуги", categoryId: "BFS_ORG_GUARANT01", categoryName: "Гарантия" },
    { status: "действующий", productId: "MMF_GIK", name: "Гарантия исполнения контракта", productType: "Финансовые услуги", categoryId: "BFS_ORG_GUARANT01", categoryName: "Гарантия" },
    { status: "действующий", productId: "MMF_GM", name: "Автокредит ММФ GM", productType: "Финансовые услуги", categoryId: "BFS_ORG_LOANO", categoryName: "Кредиты за счет собств. средств" },
    { status: "действующий", productId: "MMF_GREEN", name: "Кредит ММФ по продукту \"GREEN ENERGY\"", productType: "Финансовые услуги", categoryId: "BFS_ORG_LOANO", categoryName: "Кредиты за счет собств. средств" },
    { status: "действующий", productId: "MMF_GT", name: "Для участия в тендере", productType: "Финансовые услуги", categoryId: "BFS_ORG_GUARANT01", categoryName: "Гарантия" },
    { status: "действующий", productId: "MMF_GTS", name: "Для организации таможенного склада", productType: "Финансовые услуги", categoryId: "BFS_ORG_GUARANT01", categoryName: "Гарантия" },
    { status: "действующий", productId: "MMF_HAM", name: "Кредит ММФ \"Женщина предприниматель\" HAM", productType: "Финансовые услуги", categoryId: "BFS_ORG_LOANO", categoryName: "Кредиты за счет собств. средств" },
    { status: "действующий", productId: "MMF_ICD", name: "Предоставление гарантии в пользу ИКРЧС", productType: "Финансовые услуги", categoryId: "BFS_ORG_GUARANT01", categoryName: "Гарантия" },
    { status: "заблокировать", productId: "MMF_IFC", name: "Кредит ММФ за счет линии МФК", productType: "Финансовые услуги", categoryId: "BFS_ORG_LOANI", categoryName: "Кредиты за счет ин. капитала" },
    { status: "действующий", productId: "MMF_IGT", name: "Кредит по продукту INTER GREEN TECHNOLOGY", productType: "Финансовые услуги", categoryId: "BFS_ORG_LOANO", categoryName: "Кредиты за счет собств. средств" },
    { status: "действующий", productId: "MMF_IK", name: "BUSINESS IPOTEKA нац валюта", productType: "Финансовые услуги", categoryId: "BFS_ORG_LOANO", categoryName: "Кредиты за счет собств. средств" },
    { status: "действующий", productId: "MMF_KFW", name: "Кредит ММФ за счет линии KFW", productType: "Финансовые услуги", categoryId: "BFS_ORG_LOANI", categoryName: "Кредиты за счет ин. капитала" },
    { status: "действующий", productId: "MMF_KL", name: "Кредит - кредитная линия возобновляемая", productType: "Финансовые услуги", categoryId: "BFS_ORG_LOANO", categoryName: "Кредиты за счет собств. средств" },
    { status: "заблокировать", productId: "MMF_LS", name: "Лизинг Малого и микрофинансирования", productType: "Финансовые услуги", categoryId: "BFS_ORG_LEASING01", categoryName: "Лизинг" },
    { status: "действующий", productId: "MMF_MAH", name: "Кредит ММФ по программе \"Махалла\"", productType: "Финансовые услуги", categoryId: "BFS_ORG_LOANO", categoryName: "Кредиты за счет собств. средств" },
    { status: "действующий", productId: "MMF_ONLINE", name: "Кредит - невозобновляемый (нац. валюта)", productType: "Финансовые услуги", categoryId: "BFS_ORG_LOANO", categoryName: "Кредиты за счет собств. средств" },
    { status: "действующий", productId: "MMF_PRPC", name: "Кредит ММФ за счет линии PROPARCO", productType: "Финансовые услуги", categoryId: "BFS_ORG_LOANI", categoryName: "Кредиты за счет ин. капитала" },
    { status: "действующий", productId: "MMF_RESP", name: "Кредит ММФ за счет линии ResponsAbility", productType: "Финансовые услуги", categoryId: "BFS_ORG_LOANI", categoryName: "Кредиты за счет ин. капитала" },
    { status: "действующий", productId: "MMF_RLS", name: "Лизинг", productType: "Финансовые услуги", categoryId: "BFS_ORG_LEASING01", categoryName: "Лизинг" },
    { status: "действующий", productId: "MMF_SLF", name: "Кредит ММФ \"Первый шаг\" нац валюта", productType: "Финансовые услуги", categoryId: "BFS_ORG_LOANI", categoryName: "Кредиты за счет ин. капитала" },
    { status: "действующий", productId: "MMF_SYMB", name: "Кредит ММФ за счет линии Symbiotics", productType: "Финансовые услуги", categoryId: "BFS_ORG_LOANI", categoryName: "Кредиты за счет ин. капитала" },
    { status: "действующий", productId: "MMF_TRM", name: "Автокредит Trend Motors", productType: "Финансовые услуги", categoryId: "BFS_ORG_LOANO", categoryName: "Кредиты за счет собств. средств" },
    { status: "действующий", productId: "MMF_USD", name: "Кредит ММФ за счет собств.средств ДОЛ", productType: "Финансовые услуги", categoryId: "BFS_ORG_LOANO", categoryName: "Кредиты за счет собств. средств" },
    { status: "действующий", productId: "MMF_VYH", name: "Автокредит VOYAH", productType: "Финансовые услуги", categoryId: "BFS_ORG_LOANO", categoryName: "Кредиты за счет собств. средств" },
    { status: "действующий", productId: "M_AVK_LI", name: "Автокредит Lixiang", productType: "Финансовые услуги", categoryId: "BFS_ORG_LOANO", categoryName: "Кредиты за счет собств. средств" },
    { status: "действующий", productId: "M_BMF_US", name: "Кредит за счет линии BlueOrchard (вал)", productType: "Финансовые услуги", categoryId: "BFS_ORG_LOANI", categoryName: "Кредиты за счет ин. капитала" },
    { status: "действующий", productId: "M_DKM_USD", name: "Кредит ММФ за счет MIKROFINANZFOND (USD)", productType: "Финансовые услуги", categoryId: "BFS_ORG_LOANI", categoryName: "Кредиты за счет ин. капитала" },
    { status: "заблокировать", productId: "M_EBR_USD", name: "Кредит ММФ за счет линии ЕБРР Доллар", productType: "Финансовые услуги", categoryId: "BFS_ORG_LOANI", categoryName: "Кредиты за счет ин. капитала" },
    { status: "действующий", productId: "M_EXP_USD", name: "BUSINESS EXPRESS Валютный", productType: "Финансовые услуги", categoryId: "BFS_ORG_LOANO", categoryName: "Кредиты за счет собств. средств" },
    { status: "заблокировать", productId: "M_FMO_USD", name: "Кредит ММФ за счет линии ФМО валютный", productType: "Финансовые услуги", categoryId: "BFS_ORG_LOANI", categoryName: "Кредиты за счет ин. капитала" },
    { status: "действующий", productId: "M_IFC_USD", name: "Кредит ММФ за счет IFC (USD)", productType: "Финансовые услуги", categoryId: "BFS_ORG_LOANI", categoryName: "Кредиты за счет ин. капитала" },
    { status: "действующий", productId: "M_IK_USD", name: "BUSINESS IPOTEKA ин. валюта", productType: "Финансовые услуги", categoryId: "BFS_ORG_LOANO", categoryName: "Кредиты за счет собств. средств" },
    { status: "действующий", productId: "M_KL_EUR", name: "Кредит - кредитная линия возобновляемая", productType: "Финансовые услуги", categoryId: "BFS_ORG_LOANO", categoryName: "Кредиты за счет собств. средств" },
    { status: "действующий", productId: "M_KL_USD", name: "Кредит - кредитная линия возобновляемая", productType: "Финансовые услуги", categoryId: "BFS_ORG_LOANO", categoryName: "Кредиты за счет собств. средств" },
    { status: "действующий", productId: "M_LS_USD", name: "Лизинг Малого и микрофинансир (валютный)", productType: "Финансовые услуги", categoryId: "BFS_ORG_LEASING01", categoryName: "Лизинг" },
    { status: "действующий", productId: "M_OPC_USD", name: "Кредит ММФ за счет линии ОПЕК Доллар", productType: "Финансовые услуги", categoryId: "BFS_ORG_LOANI", categoryName: "Кредиты за счет ин. капитала" },
    { status: "действующий", productId: "M_PRPC_US", name: "Кредит ММФ за счет линии PROPARCO (вал)", productType: "Финансовые услуги", categoryId: "BFS_ORG_LOANI", categoryName: "Кредиты за счет ин. капитала" },
    { status: "действующий", productId: "M_RESP_US", name: "Кредит ММФ за счет линии ResponsAbility", productType: "Финансовые услуги", categoryId: "BFS_ORG_LOANI", categoryName: "Кредиты за счет ин. капитала" },
    { status: "действующий", productId: "M_SLF_AVK", name: "Кредит ММФ \"Первый шаг\" (авто кредит)", productType: "Финансовые услуги", categoryId: "BFS_ORG_LOANO", categoryName: "Кредиты за счет собств. средств" },
    { status: "действующий", productId: "M_SLF_EUR", name: "Кредит ММФ \"Первый шаг\" иност валют ЕВРО", productType: "Финансовые услуги", categoryId: "BFS_ORG_LOANO", categoryName: "Кредиты за счет собств. средств" },
    { status: "действующий", productId: "M_SLF_MAH", name: "Кредит ММФ СЗФЛ \"Махалла\"", productType: "Финансовые услуги", categoryId: "BFS_ORG_LOANO", categoryName: "Кредиты за счет собств. средств" },
    { status: "действующий", productId: "M_SLF_USD", name: "Кредит ММФ \"Первый шаг\" иност валюта", productType: "Финансовые услуги", categoryId: "BFS_ORG_LOANI", categoryName: "Кредиты за счет ин. капитала" },
    { status: "действующий", productId: "M_SLF_VYH", name: "Кредит ММФ \"Первый шаг\" (авто кредит)", productType: "Финансовые услуги", categoryId: "BFS_ORG_LOANO", categoryName: "Кредиты за счет собств. средств" },
    { status: "действующий", productId: "M_SL_DR", name: "Кредит СЗФЛ за счет собственных средств", productType: "Финансовые услуги", categoryId: "BFS_ORG_LOANO", categoryName: "Кредиты за счет собств. средств" },
    { status: "действующий", productId: "M_SL_GM", name: "Кредит ММФ GM (автокредит)", productType: "Финансовые услуги", categoryId: "BFS_ORG_LOANO", categoryName: "Кредиты за счет собств. средств" },
    { status: "действующий", productId: "M_SL_KR", name: "Кредит СЗФЛ за счет собственных средств", productType: "Финансовые услуги", categoryId: "BFS_ORG_LOANO", categoryName: "Кредиты за счет собств. средств" },
    { status: "действующий", productId: "M_SMB_EUR", name: "Кредит ММФ за счет линии Symbiotics Евро", productType: "Финансовые услуги", categoryId: "BFS_ORG_LOANI", categoryName: "Кредиты за счет ин. капитала" },
    { status: "действующий", productId: "M_SYMB_US", name: "Кредит ММФ за счет линии Symbiotics USD", productType: "Финансовые услуги", categoryId: "BFS_ORG_LOANI", categoryName: "Кредиты за счет ин. капитала" },
    { status: "действующий", productId: "M_TRJP_US", name: "Кредит ММФ за счет линии TRJP валютный", productType: "Финансовые услуги", categoryId: "BFS_ORG_LOANI", categoryName: "Кредиты за счет ин. капитала" },
    { status: "открыть", productId: "", name: "Кредит ММФ за счет линии DWM Asset managment", productType: "Финансовые услуги", categoryId: "BFS_ORG_LOANI", categoryName: "Кредиты за счет ин. капитала" },
    { status: "открыть", productId: "", name: "Кредит ММФ за счет линии Japan International Cooperation Agency", productType: "Финансовые услуги", categoryId: "BFS_ORG_LOANI", categoryName: "Кредиты за счет ин. капитала" },
    { status: "действующий", productId: "M_UN / M_UN_VAL", name: "Универсальный продукт", productType: "Финансовые услуги", categoryId: "", categoryName: "В зависимости от выбранного Шифра источника финансирования" },
  ];

  for (const sc of sapCodes) {
    await db.insert(sapCodesTable).values(sc);
  }
  console.log(`Inserted ${sapCodes.length} SAP codes`);

  console.log("Seeding credit lines...");
  await db.delete(creditLinesTable);

  const creditLines = [
    { number: 1, name: "Symbiotics Sicav Asset Management", department: "Корп/Микро", agreementDate: "2023-12-08", agreementAmount: "4000000", receivedAmount: "4000000", currency: "EUR (978)", interestRate: "6.15%", disbursedAmount: "3551044.99", remainingBalance: "448955.01", projectCount: 71, specialConditions: "Линия направлена на развитие ММСБ", notes: "нет изменений", section: "Доступные для освоения" },
    { number: 2, name: "Proparco", department: "Микро/Корп", agreementDate: "2024-03-05", agreementAmount: "30000000", receivedAmount: "381238500000", currency: "UZS (000)", interestRate: "8.5%", disbursedAmount: "232697865697.61", remainingBalance: "148540634302.39", projectCount: 893, specialConditions: "МСБ годовой объем продаж составляет менее 15 000 000 долларов США в эквиваленте; общая сумма активов составляет менее эквивалент 15 000 000 долларов США; и в компании работает менее 300 сотрудников", notes: "", section: "Доступные для освоения" },
    { number: 3, name: "KfW", department: "Микро", agreementDate: "2024-12-28", agreementAmount: "8400000", receivedAmount: "117879972000", currency: "UZS (000)", interestRate: "Ставка Рефин.ЦБ.РУз.", disbursedAmount: "75087166934.37", remainingBalance: "42792805065.63", projectCount: 131, specialConditions: "Согласно паспорту продукта", notes: "", section: "Доступные для освоения" },
    { number: 4, name: "DWM Asset managment", department: "Микро", agreementDate: "2024-06-30", agreementAmount: "4300000", receivedAmount: "54288274000", currency: "UZS (000)", interestRate: "22.5%", disbursedAmount: "0", remainingBalance: "54288274000", projectCount: 0, specialConditions: "Линия направлена на развитие ММСБ", notes: "", section: "Доступные для освоения" },
    { number: 5, name: "АБР", department: "Микро", agreementDate: "2024-11-05", agreementAmount: "20000000", receivedAmount: "10200000", currency: "USD (840)", interestRate: "7.8%", disbursedAmount: "0", remainingBalance: "10200000", projectCount: 0, specialConditions: "На развитие ММСБ, юридическое местонахождение и основной бизнес которых находятся за пределами города Ташкент", notes: "", section: "Доступные для освоения" },
    { number: 6, name: "АБР", department: "Микро", agreementDate: "2024-11-05", agreementAmount: "20000000", receivedAmount: "1200000", currency: "USD (840)", interestRate: "7.8%", disbursedAmount: "0", remainingBalance: "1200000", projectCount: 0, specialConditions: "Для \"Женское предпринимательство\" за пределами города Ташкент.", notes: "", section: "Доступные для освоения" },
    { number: 7, name: "АБР", department: "Микро", agreementDate: "2024-11-05", agreementAmount: "20000000", receivedAmount: "600000", currency: "USD (840)", interestRate: "7.8%", disbursedAmount: "0", remainingBalance: "600000", projectCount: 0, specialConditions: "Для \"Зеленая экономика\" за пределами города Ташкент", notes: "", section: "Доступные для освоения" },
    { number: 8, name: "АБР", department: "Микро", agreementDate: "2024-11-05", agreementAmount: "20000000", receivedAmount: "7160000", currency: "USD (840)", interestRate: "7.8%", disbursedAmount: "33141.80", remainingBalance: "7126858.20", projectCount: 1, specialConditions: "На развитие ММСБ для г.Ташкент", notes: "", section: "Доступные для освоения" },
    { number: 9, name: "АБР", department: "Микро", agreementDate: "2024-11-05", agreementAmount: "20000000", receivedAmount: "800000", currency: "USD (840)", interestRate: "7.8%", disbursedAmount: "0", remainingBalance: "800000", projectCount: 0, specialConditions: "Для \"Женское предпринимательство\" г. Ташкент", notes: "", section: "Доступные для освоения" },
    { number: 10, name: "АБР", department: "Микро", agreementDate: "2024-11-05", agreementAmount: "20000000", receivedAmount: "40000", currency: "USD (840)", interestRate: "7.8%", disbursedAmount: "0", remainingBalance: "40000", projectCount: 0, specialConditions: "Для \"Зеленая экономика\" г.Ташкент", notes: "", section: "Доступные для освоения" },
    { number: 11, name: "OPEC", department: "Микро", agreementDate: "2024-11-23", agreementAmount: "30000000", receivedAmount: "15000000", currency: "USD (840)", interestRate: "SOFR+3,6%", disbursedAmount: "15158937.46", remainingBalance: "-158937.46", projectCount: 197, specialConditions: "Линия направлена на развитие ММСБ", notes: "", section: "Доступные для освоения" },
    { number: 12, name: "IFC (МФК)", department: "Микро", agreementDate: "2024-09-21", agreementAmount: "42000000", receivedAmount: "42000000", currency: "USD (840)", interestRate: "7,682% до 15.03.2024", disbursedAmount: "1180721.74", remainingBalance: "40819278.26", projectCount: 23, specialConditions: "Сумма одного проекта не должно превышать 1 000 000,00 долл.США или эквивалент в национальной валюте.", notes: "25% суммы соглашения должны направляться для развития \"Женское предпринимательство\" ММСБ. Сумма одного проекта не должно превышать 1 000 000,00 долл.США или эквивалент в национальной валюте.", section: "Доступные для освоения" },
    { number: 13, name: "HANSAINVEST (IIV Mikrofinanzfonds)", department: "Корп/Микро (Сумма одного проекта не должно превышать 30k USD)", agreementDate: "2023-12-15", agreementAmount: "7000000", receivedAmount: "7000000", currency: "USD (840)", interestRate: "7.8%", disbursedAmount: "0", remainingBalance: "7000000", projectCount: 0, specialConditions: "(Сумма одного проекта не должно превышать 30k USD)", notes: "нет изменений", section: "Доступные для освоения" },
    { number: 14, name: "BlueOrchard Microfinance Fund", department: "Корп", agreementDate: "2025-06-20", agreementAmount: "25000000", receivedAmount: "25000000", currency: "USD (840)", interestRate: "6 мес.Term SOFR+3,30%", disbursedAmount: "15052034.48", remainingBalance: "9947965.52", projectCount: 106, specialConditions: "не имеет особых условий", notes: "", section: "Доступные для освоения" },
    { number: 15, name: "Голландский банк развития (FMO)", department: "Микро", agreementDate: "2025-02-07", agreementAmount: "45500000", receivedAmount: "547042860000", currency: "UZS (000)", interestRate: "15.43%", disbursedAmount: "152239403911.09", remainingBalance: "394803456088.91", projectCount: 484, specialConditions: "1) Женщина-предприниматель-51% и больше доли юридического лица принадлежит женщине", notes: "", section: "Доступные для освоения" },
    { number: 16, name: "Голландский банк развития (FMO)", department: "Микро", agreementDate: "2025-02-07", agreementAmount: "19500000", receivedAmount: "19500000", currency: "USD (840)", interestRate: "6 мес.Term SOFR+3,30%", disbursedAmount: "0", remainingBalance: "19500000", projectCount: 0, specialConditions: "1) Женщина-предприниматель-51% и больше доли юридического лица принадлежит женщине", notes: "", section: "Доступные для освоения" },
    { number: 17, name: "ResponsAbility (Швейцария)", department: "Микро", agreementDate: "2025-12-17", agreementAmount: "5000000", receivedAmount: "5000000", currency: "USD (840)", interestRate: "6 мес.Term SOFR+3,4%", disbursedAmount: "5180328.77", remainingBalance: "-180328.77", projectCount: 78, specialConditions: "Линия направлена на развитие ММСБ", notes: "", section: "Доступные для освоения" },
    { number: 18, name: "NTB", department: "Микро/Розница", agreementDate: "2025-07-12", agreementAmount: "20000000", receivedAmount: "20000000", currency: "USD (840)", interestRate: "6 мес.Term SOFR+3,25%", disbursedAmount: "0", remainingBalance: "20000000", projectCount: 0, specialConditions: "не имеет особых условий", notes: "", section: "Доступные для освоения" },
    { number: 19, name: "Monega Mikrofinanz & Impact Fonds (DWM Asset management)", department: "Микро", agreementDate: "2024-07-07", agreementAmount: "500000", receivedAmount: "500000", currency: "EUR (978)", interestRate: "7%", disbursedAmount: "0", remainingBalance: "500000", projectCount: 0, specialConditions: "Линия направлена на развитие ММСБ", notes: "", section: "Доступные для освоения" },
    { number: 20, name: "Cardano Impact под управлением DWM Asset management", department: "Микро/Корп", agreementDate: "2024-06-17", agreementAmount: "6000000", receivedAmount: "6000000", currency: "EUR (978)", interestRate: "7%", disbursedAmount: "0", remainingBalance: "6000000", projectCount: 0, specialConditions: "не имеет особых условий", notes: "", section: "Доступные для освоения" },
    { number: 21, name: "DWM Income Funds", department: "Микро", agreementDate: "2025-09-23", agreementAmount: "1000000", receivedAmount: "12581730000", currency: "UZS (000)", interestRate: "18%", disbursedAmount: "0", remainingBalance: "12581730000", projectCount: 0, specialConditions: "Линия направлена на развитие ММСБ", notes: "", section: "Доступные для освоения" },
    { number: 22, name: "Enabling Qapital AG", department: "Микро", agreementDate: "2024-04-01", agreementAmount: "10000000", receivedAmount: "10000000", currency: "USD (840)", interestRate: "8.5%", disbursedAmount: "0", remainingBalance: "10000000", projectCount: 0, specialConditions: "не имеет особых условий", notes: "", section: "Доступные для освоения" },
    { number: 23, name: "Volksvermorgen", department: "Микро", agreementDate: "2024-08-14", agreementAmount: "1000000", receivedAmount: "1000000", currency: "EUR (978)", interestRate: "7.97%", disbursedAmount: "0", remainingBalance: "1000000", projectCount: 0, specialConditions: "Линия направлена на развитие ММСБ", notes: "", section: "Доступные для освоения" },
    { number: 24, name: "Incofin", department: "Микро", agreementDate: "2024-06-25", agreementAmount: "2500000", receivedAmount: "2673750", currency: "USD (840)", interestRate: "c 27.06.24 по 27.12.24 11,081%", disbursedAmount: "0", remainingBalance: "2673750", projectCount: 0, specialConditions: "Линия направлена на развитие ММСБ", notes: "", section: "Доступные для освоения" },
  ];

  for (const cl of creditLines) {
    await db.insert(creditLinesTable).values(cl);
  }
  console.log(`Inserted ${creditLines.length} credit lines`);

  console.log("Seeding complete!");
  process.exit(0);
}

seed().catch(e => { console.error(e); process.exit(1); });
