#!/usr/bin/env tsx
/**
 * Render the roles-and-permissions matrix to docs/roles-and-permissions.md.
 *
 * The matrix is generated from `src/rbac/permissions.ts` and
 * `src/rbac/role-permissions.ts`. Do not edit the generated markdown by hand;
 * change the source files and re-run this script.
 *
 * Usage:
 *   pnpm --filter @workspace/api-server run render:permissions-doc
 */
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { ROLE_PERMISSIONS, ROLES } from "../src/rbac/role-permissions";
import { PERMISSIONS } from "../src/rbac/permissions";

const cell = (has: boolean) => (has ? "✓" : "—");
const header = ["Permission", ...ROLES].join(" | ");
const sep = ["---", ...ROLES.map(() => "---")].join(" | ");
const rows = PERMISSIONS.map((p) => {
  const roleCells = ROLES.map((r) => cell(ROLE_PERMISSIONS[r].includes(p)));
  return [p, ...roleCells].join(" | ");
});

const md = [
  "# Roles and Permissions",
  "",
  "Auto-generated by `artifacts/api-server/scripts/render-permissions-doc.ts`.",
  "Do not edit by hand. To update, change `role-permissions.ts` and re-run:",
  "",
  "    pnpm --filter @workspace/api-server run render:permissions-doc",
  "",
  `| ${header} |`,
  `| ${sep} |`,
  ...rows.map((r) => `| ${r} |`),
  "",
].join("\n");

const outPath = resolve(process.cwd(), "docs/roles-and-permissions.md");
writeFileSync(outPath, md);
console.log(`wrote ${outPath}`);
